version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geopark_back_end
    logging:
        options:
          max-size: 10m
          max-file: "3"
    ports:
      - "5437:5432"
    volumes:
      - ./db:/var/lib/postgresql/data/